name: plasma_furnace_ui
description: Simulador de Fornalha de Plasma para pesquisa de incineração de resíduos.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  fl_chart: ^0.65.0
  flutter_gl: ^0.0.21
  path_provider: ^2.1.1
  file_picker: ^10.1.2
  json_annotation: ^4.8.1
  ffi: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
